'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Locale = 'en' | 'am';

type Translations = Record<string, string>;

const amharicTranslations: Translations = {
  // Sidebar
  'sidebar.main': 'ዋና',
  'sidebar.management': 'አስተዳደር',
  'sidebar.settings': 'ቅንብሮች',
  'sidebar.dashboard': 'ዳሽቦርድ',
  'sidebar.passports': 'ፓስፖርቶች',
  'sidebar.boxes': 'ሳጥኖች',
  'sidebar.structure': 'መዋቅር',
  'sidebar.logs': 'የኦዲት መዝገቦች',
  'sidebar.profile': 'መገለጫ',
  'sidebar.security': 'ደህንነት',
  'sidebar.setup': 'ማዋቀር',
  'sidebar.reports': 'ሪፖርቶች',
  'sidebar.logout': 'ውጣ',

  // Header
  'header.search_placeholder': 'ፓስፖርቶች፣ ሳጥኖች፣ ቦታዎችን ፈልግ...',
  'header.profile_tooltip': 'መገለጫ እይ',
  'header.search_no_results': 'ምንም ውጤት አልተገኘም',
  'header.search_searching': 'በመፈለግ ላይ...',
  'header.search_min_char': 'ቢያንስ 2 ቁምፊዎችን ያስገቡ',

  // Dashboard
  'dashboard.title': 'የዳሽቦርድ አጠቃላይ እይታ',
  'dashboard.subtitle': 'የእውነተኛ ጊዜ ክትትል ማጠቃለያ',
  'dashboard.total_boxes': 'አጠቃላይ ተንቀሳቃሽ ሳጥኖች',
  'dashboard.total_boxes_sub': 'ሁሉም የተመዘገቡ ሳጥኖች',
  'dashboard.occupied_boxes': 'የተያዙ ሳጥኖች',
  'dashboard.occupied_boxes_sub': 'በአሁኑ ጊዜ በጥቅም ላይ ያሉ',
  'dashboard.vacant_boxes': 'ክፍት ሳጥኖች',
  'dashboard.vacant_boxes_sub': 'ለአገልግሎት ዝግጁ የሆኑ',
  'dashboard.occupancy_rate': 'የመያዝ መጠን',
  'dashboard.occupancy_rate_sub': 'አጠቃላይ አጠቃቀም',
  'dashboard.table_title': 'የተንቀሳቃሽ ሳጥን አጠቃላይ እይታ',
  'dashboard.refresh': 'አድስ',
  'dashboard.showing_recent': 'የቅርብ ጊዜዎቹን እያሳየ ነው',
  'dashboard.view_all': 'ሁሉንም እይ',
  'dashboard.col_box_id': 'የሳጥን መለያ',
  'dashboard.col_label': 'ስም',
  'dashboard.col_location': 'ቦታ',
  'dashboard.col_occupied': 'የተያዙ',
  'dashboard.col_capacity': 'አቅም',
  'dashboard.col_status': 'ሁኔታ',
  'dashboard.loading_stats': 'የዳሽቦርድ ስታቲስቲክስ በመጫን ላይ...',
  'dashboard.activity_trend': 'የፓስፖርት እንቅስቃሴ አዝማሚያ',
  'dashboard.activity_trend_sub': 'ሳምንታዊ የፓስፖርት መመለስ እና መስጠት መጠን',
  'dashboard.room_capacity': 'የክፍል ማከማቻ አቅም አጠቃቀም',
  'dashboard.room_capacity_sub': 'የተያዙ ቦታዎች ከጠቅላላው አቅም አንጻር',

  // Passports page
  'passports.title': 'የፓስፖርት ምዝገባ',
  'passports.subtitle': 'ሁሉንም ፓስፖርቶች ያስተዳድሩ እና ይከታተሉ',
  'passports.add_passport': 'አዲስ ፓስፖርት ይመዝግቡ',
  'passports.search_placeholder': 'በስም ፣ በመለያ ቁጥር ወይም በQR ፈልግ...',
  'passports.col_holder': 'ባለቤት',
  'passports.col_passport_no': 'የፓስፖርት ቁጥር',
  'passports.col_qr_code': 'የQR ኮድ',
  'passports.col_status': 'ሁኔታ',
  'passports.status_active': 'ንቁ',
  'passports.status_inactive': 'ያልነቃ',
  'passports.custody_title': 'የፓስፖርት ጥበቃ ስርዓት',
  'passports.custody_subtitle': 'ብሄራዊ ፓስፖርቶችን ይመዝግቡ እና ይከታተሉ',
  'passports.custody_subtitle_count': 'አጠቃላይ ፓስፖርቶች በዳታቤዝ ውስጥ',
  'passports.all_title': 'ሁሉም የተመዘገቡ ፓስፖርቶች',
  'passports.all_statuses': 'ሁሉም ሁኔታዎች',
  'passports.status_in_box': 'ሳጥን ውስጥ',
  'passports.status_issued': 'የተሰጠ',
  'passports.selected_count': 'የተመረጡ ፓስፖርቶች',
  'passports.batch_assign': 'በቡድን ወደ ሳጥን መድብ',
  'passports.clear_selection': 'ምርጫውን ሰርዝ',
  'passports.col_holder_id': 'የመለያ ቁጥር',
  'passports.col_box': 'የሳጥን ማከማቻ',
  'passports.col_actions': 'ተግባራት',
  'passports.action_move': 'አንቀሳቅስ',
  'passports.action_return': 'መልስ',
  'passports.action_issue': 'ስጥ',
  'passports.no_results': 'ምንም ፓስፖርት አልተገኘም',
  'passports.no_records': 'ምንም የተመዘገበ ፓስፖርት የለም',
  'passports.try_different': 'ሌላ ፍለጋ ወይም ማጣሪያ ይሞክሩ',
  'passports.register_to_begin': 'ክትትል ለመጀመር አዲስ ፓስፖርት ይመዝግቡ',
  'passports.prev': 'ቀዳሚ',
  'passports.next': 'ቀጣይ',
  'passports.of': 'ከ',
  'passports.records': 'መዝገቦች',
  'passports.modal_register_title': 'አዲስ ፓስፖርት ይመዝግቡ',
  'passports.field_qr': 'የQR ኮድ / የሰነድ ቁጥር *',
  'passports.field_name': 'የባለቤት ሙሉ ስም *',
  'passports.field_id': 'ብሄራዊ / የመታወቂያ ቁጥር *',
  'passports.cancel': 'ሰርዝ',
  'passports.registering': 'በመመዝገብ ላይ...',
  'passports.register': 'መዝግብ',
  'passports.modal_batch_title': 'በቡድን ወደ ተንቀሳቃሽ ሳጥን መድብ',
  'passports.modal_assign_title': 'ፓስፖርት ወደ ሳጥን መድብ',
  'passports.selected_count_sub': 'የተመረጡ ፓስፖርቶች',
  'passports.boxes_avail': 'ሳጥኖች ይገኛሉ',
  'passports.passport_of': 'የሆነው ፓስፖርት',
  'passports.search_box_placeholder': 'በስም ወይም በQR ኮድ ፈልግ...',
  'passports.loading_boxes': 'ሳጥኖች በመጫን ላይ...',
  'passports.no_available_boxes': 'በቂ ክፍት ቦታ ያላቸው ሳጥኖች የሉም',
  'passports.need_boxes_with': 'ቢያንስ ይህን ያህል ክፍት ቦታ ያላቸው ሳጥኖች ያስፈልጋሉ',
  'passports.vacant_slots': 'ክፍት ቦታዎች',
  'passports.vacant_count': 'ክፍት ቦታ',
  'passports.assigning': 'በመመደብ ላይ...',
  'passports.assign': 'መድብ',
  'passports.modal_issue_title': 'ፓስፖርት ስጥ',
  'passports.issue_msg_1': 'የሆነውን ፓስፖርት',
  'passports.issue_msg_2': 'ለባለቤቱ ለመስጠት ይፈልጋሉ?',
  'passports.modal_delete_title': 'መሰረዙን ያረጋግጡ',
  'passports.delete_msg_1': 'የሆነውን ፓስፖርት ለመሰረዝ እርግጠኛ ነዎት?',
  'passports.delete_msg_2': 'ይህ ድርጊት ወደኋላ መመለስ አይቻልም።',
  'passports.delete': 'ሰርዝ',

  // Boxes page
  'boxes.title': 'ተንቀሳቃሽ ሳጥኖች',
  'boxes.subtitle': 'የሳጥኖችን ዝርዝር ሁኔታ እና ምደባ ያስተዳድሩ',
  'boxes.add_box': 'አዲስ ሳጥን ጨምር',
  'boxes.all_title': 'ሁሉም ተንቀሳቃሽ ሳጥኖች',
  'boxes.selected_count': 'የተመረጡ ሳጥኖች',
  'boxes.total_count': 'ሳጥኖች በስርዓቱ ውስጥ',
  'boxes.assign_to_slots': 'ሳጥኖችን ወደ ቦታዎች መድብ',
  'boxes.bulk_register': 'በጅምላ መዝግብ',
  'boxes.search_placeholder': 'የሳጥን መለያ፣ ስም ፈልግ...',
  'boxes.all_status': 'ሁሉም ሁኔታ',
  'boxes.status_active': 'ንቁ',
  'boxes.status_full': 'ሞልቷል',
  'boxes.status_inactive': 'ያልነቃ',
  'boxes.col_box_id': 'የሳጥን መለያ',
  'boxes.col_label': 'ስም',
  'boxes.col_location': 'ቦታ',
  'boxes.col_occupied': 'የተያዘ',
  'boxes.col_capacity': 'አቅም',
  'boxes.col_status': 'ሁኔታ',
  'boxes.col_actions': 'ተግባራት',
  'boxes.unassigned': 'ያልተመደበ',
  'boxes.action_move_tooltip': 'ወደ ቦታ አንቀሳቅስ',
  'boxes.cannot_delete_occupied': 'የተያዘ ሳጥን መሰረዝ አይቻልም',
  'boxes.delete_box': 'ሳጥን ሰርዝ',
  'boxes.no_results': 'ምንም ሳጥን አልተገኘም',
  'boxes.no_records': 'ምንም የተመዘገበ ሳጥን የለም',
  'boxes.try_different': 'ሌላ ፍለጋ ወይም ማጣሪያ ይሞክሩ',
  'boxes.add_to_begin': 'ሳጥን በመጨመር ይጀምሩ',
  'boxes.modal_create_title': 'አዲስ ሳጥን ጨምር',
  'boxes.field_qr': 'የQR ኮድ *',
  'boxes.field_label': 'ስም *',
  'boxes.field_capacity': 'አቅም',
  'boxes.capacity_help': 'ነባሪ አቅም በአንድ ሳጥን 10 ፓስፖርት ነው',
  'boxes.creating': 'በመፍጠር ላይ...',
  'boxes.create': 'ሳጥን ፍጠር',
  'boxes.modal_move_title': 'ሳጥን አንቀሳቅስ',
  'boxes.select_slot_help': 'ይህንን ሳጥን ለመመደብ ቦታ ይምረጡ',
  'boxes.slots_available': 'ክፍት ቦታዎች ይገኛሉ',
  'boxes.search_slot_placeholder': 'ቦታ በስም፣ ክፍል ወይም በQR ኮድ ፈልግ...',
  'boxes.no_slots_found': 'ለፍለጋዎ የሚስማማ ቦታ አልተገኘም',
  'boxes.no_slots_configured': 'ምንም የተዋቀረ ቦታ የለም',
  'boxes.moving': 'በማንቀሳቀስ ላይ...',
  'boxes.modal_bulk_title': 'ሳጥኖችን በጅምላ መዝግብ',
  'boxes.bulk_register_help': 'ቅደም ተከተል ባለው ስያሜ ብዙ ሳጥኖችን በአንድ ጊዜ ይመዝግቡ',
  'boxes.field_label_pattern': 'የስም ንድፍ',
  'boxes.label_pattern_help': 'ለቁጥር {n} ይጠቀሙ። ዜሮ ለመጨመር :04d ይጨምሩ...',
  'boxes.field_qr_pattern': 'የQR ኮድ ንድፍ',
  'boxes.qr_pattern_help': 'የQR ኮዶች ልዩ መሆን አለባቸው። እንደ ስሙ ተመሳሳይ ንድፍ ይጠቀሙ።',
  'boxes.field_start_number': 'መጀመሪያ ቁጥር',
  'boxes.field_end_number': 'መጨረሻ ቁጥር',
  'boxes.preview': 'ቅድመ እይታ',
  'boxes.boxes_count_suffix': 'ሳጥኖች',
  'boxes.and': 'እና',
  'boxes.more': 'ተጨማሪ',
  'boxes.registering': 'በመመዝገብ ላይ...',
  'boxes.register': 'መዝግብ',
  'boxes.modal_bulk_assign_title': 'ሳጥኖችን በጅምላ ወደ ቦታዎች መድብ',
  'boxes.bulk_assign_help': 'የተመረጡትን ሳጥኖች በራስ-ሰር ወደሚገኙ ቦታዎች መድብ',
  'boxes.field_room_filter': 'በክፍል አጣራ (አማራጭ)',
  'boxes.all_rooms': 'ሁሉም ክፍሎች (ማንኛውም የሚገኝ ቦታ)',
  'boxes.assign_slots_help': 'ሳጥኖች መጀመሪያ ወደሚገኙት ክፍት ቦታዎች ይመደባሉ',
  'boxes.in_room': 'በተመረጠው ክፍል ውስጥ',
  'boxes.selected_boxes_heading': 'የተመረጡ ሳጥኖች',
  'boxes.assigning': 'በመመደብ ላይ...',
  'boxes.assign': 'መድብ',
  'boxes.delete_confirm_msg': 'ይህንን ሳጥን ለመሰረዝ እርግጠኛ ነዎት? ይህ ድርጊት ወደኋላ መመለስ አይቻልም።',

  // Structure page
  'structure.title': 'የአካላዊ መዋቅር አቀማመጥ',
  'structure.subtitle': 'የማከማቻ ቦታዎችን እና መዋቅርን ያስተዳድሩ',
  'structure.structure_details': 'የመዋቅር ዝርዝር',
  'structure.room_details': 'የክፍል ዝርዝር',
  'structure.shelf_details': 'የመደርደሪያ ዝርዝር',
  'structure.row_details': 'የረድፍ ዝርዝር',
  'structure.slot_details': 'የቦታ ዝርዝር',
  'structure.hierarchy': 'የማከማቻ መዋቅር ቅደም-ተከተል',
  'structure.central_repo': 'ማዕከላዊ የመረጃ ቋት (CRS-01)',
  'structure.add_room': 'ክፍል ጨምር',
  'structure.no_rooms': 'ምንም ክፍሎች አልተዋቀሩም',
  'structure.add_room_to_begin': 'አንድ ክፍል በመጨመር ይጀምሩ።',
  'structure.details': 'ዝርዝሮች',
  'structure.details_title': 'የዝርዝር መግለጫ ሰሌዳ',
  'structure.select_item_to_view': 'ዝርዝሩን ለማየት በመዋቅሩ ዛፍ ውስጥ ያለን ነገር ይምረጡ',
  'structure.location_path': 'የቦታው መገኛ መስመር',
  'structure.qr_code': 'የQR ኮድ',
  'structure.status': 'ሁኔታ',
  'structure.occupied': 'ተይዟል',
  'structure.available': 'ክፍት',
  'structure.assign_box_to_slot': 'ሳጥን ወደ ቦታው መድብ',
  'structure.room_name': 'የክፍል ስም',
  'structure.shelf_name': 'የመደርደሪያ ስም',
  'structure.row_name': 'የረድፍ ስም',
  'structure.slot_name': 'የቦታ ስም',
  'structure.details_shelves': 'በውስጡ {count} መደርደሪያዎች ይዟል',
  'structure.details_rows': 'በውስጡ {count} ረድፎች ይዟል',
  'structure.details_slots': 'በውስጡ {count} ቦታዎች ይዟል',
  'structure.created_at': 'የተፈጠረበት ቀን',
  'structure.parent_room': 'ዋና ክፍል',
  'structure.parent_shelf': 'ዋና መደርደሪያ',
  'structure.position': 'ቅደም-ተከተል (ቦታ)',
  'structure.add': 'ጨምር',
  'structure.edit': 'አሻሽል',
  'structure.save': 'አስቀምጥ',
  'structure.saving': 'በማስቀመጥ ላይ...',
  'structure.creating': 'በመፍጠር ላይ...',
  'structure.cancel': 'ሰርዝ',
  'structure.name': 'ስም',
  'structure.position_label': 'አቀማመጥ',
  'structure.no_boxes_available': 'ምንም የሚገኙ ሳጥኖች የሉም',
  'structure.bulk_create_slots': 'ቦታዎችን በጅምላ ፍጠር',
  'structure.bulk_create_slots_help': 'ቅደም ተከተል ባለው ስያሜ ብዙ ቦታዎችን በአንድ ጊዜ ይፍጠሩ',
  'structure.name_pattern': 'የስም ንድፍ',
  'structure.qr_pattern': 'የQR ኮድ ንድፍ',
  'structure.use_n_placeholder': 'ለቁጥር placeholder {n} ይጠቀሙ (ለምሳሌ: "ቦታ {n}" → ቦታ 1, ቦታ 2...)',
  'structure.use_qr_placeholder': 'ለቁጥር {n}፣ ለረድፍ ስም {row} ይጠቀሙ (ለምሳሌ: "SLOT-{row}-{n}" → SLOT-A-1, SLOT-A-2...)',
  'structure.current_row': 'የአሁኑ ረድፍ:',
  'structure.start_number': 'መጀመሪያ ቁጥር',
  'structure.end_number': 'መጨረሻ ቁጥር',
  'structure.position_start': 'መጀመሪያ አቀማመጥ',
  'structure.preview': 'ቅድመ እይታ',
  'structure.preview_slots_title': 'ቅድመ እይታ (ከ {total} ውስጥ የመጀመሪያዎቹ 3 ቦታዎች):',
  'structure.and_more': '... እና {count} ተጨማሪ',
  'structure.create_slots_btn': '{count} ቦታዎችን ፍጠር',
  'structure.bulk_create_rows': 'ረድፎችን በጅምላ ፍጠር',
  'structure.bulk_create_rows_help': 'ፊደላትን በመጠቀም ብዙ ረድፎችን በአንድ ጊዜ ይፍጠሩ (A-Z)',
  'structure.use_letter_placeholder': 'ለፊደል placeholder {letter} ይጠቀሙ (ለምሳሌ: "ረድፍ {letter}" → ረድፍ A, ረድፍ B...)',
  'structure.use_qr_letter_placeholder': 'ለፊደል placeholder {letter} ይጠቀሙ (ለምሳሌ: "ROW-{letter}" → ROW-A, ROW-B...)',
  'structure.letter_sequence': 'የፊደል ቅደም-ተከተል',
  'structure.sequence_help': 'ቅርጸት: መጀመሪያ-መጨረሻ (ለምሳሌ: "A-Z" ለሁሉም ፊደላት, "A-J" ለመጀመሪያዎቹ 10)',
  'structure.preview_first_3': 'ቅድመ እይታ (የመጀመሪያዎቹ 3):',
  'structure.and_more_total': '... እና {count} ተጨማሪ ({total} ጠቅላላ)',
  'structure.create_rows_btn': 'ረድፎችን ፍጠር {sequence}',
  'structure.confirm_delete': 'መሰረዝን ያረጋግጡ',
  'structure.confirm_delete_msg': 'እርግጠኛ ነዎት {name} መሰረዝ ይፈልጋሉ? ይህ ድርጊት ወደኋላ መመለስ አይቻልም።',
  'structure.delete': 'ሰርዝ',
  'structure.edit_room': 'ክፍል አሻሽል',
  'structure.add_shelf': 'መደርደሪያ ጨምር',
  'structure.edit_shelf': 'መደርደሪያ አሻሽል',
  'structure.add_row': 'ረድፍ ጨምር',
  'structure.edit_row': 'ረድፍ አሻሽል',
  'structure.add_slot': 'ቦታ ጨምር',
  'structure.edit_slot': 'ቦታ አሻሽል',
  'structure.bulk_rows_btn': 'በጅምላ',
  'structure.bulk_slots_btn': 'በጅምላ',

  // Logs page
  'logs.title': 'የስርዓት ኦዲት መዝገቦች',
  'logs.subtitle': 'የስርዓት እንቅስቃሴዎችን እና እንቅስቃሴዎችን ይከታተሉ',
  'logs.activity_timeline': 'የእንቅስቃሴ የጊዜ መስመር',
  'logs.entries_found': 'የተገኙ መዝገቦች ብዛት',
  'logs.text_search': 'የጽሑፍ ፍለጋ',
  'logs.search_placeholder': 'ባለቤትን፣ QRን፣ ሳጥንን፣ ሰራተኛን ፈልግ...',
  'logs.action_type': 'የእንቅስቃሴ አይነት',
  'logs.all_actions': 'ሁሉም እንቅስቃሴዎች',
  'logs.physical_movements': 'አካላዊ እንቅስቃሴዎች',
  'logs.passport_assigned': 'ፓስፖርት ተቀምጧል',
  'logs.passport_returned': 'ወደ ካዝና የተመለሰ',
  'logs.passport_issued': 'ለባለቤቱ የተሰጠ',
  'logs.box_moved': 'ሳጥን ተንቀሳቅሷል',
  'logs.config_changes': 'የአወቃቀር ለውጦች',
  'logs.room_created': 'ክፍል ተፈጥሯል',
  'logs.room_updated': 'ክፍል ተሻሽሏል',
  'logs.room_deleted': 'ክፍል ተሰርዟል',
  'logs.shelf_created': 'መደርደሪያ ተፈጥሯል',
  'logs.shelf_updated': 'መደርደሪያ ተሻሽሏል',
  'logs.shelf_deleted': 'መደርደሪያ ተሰርዟል',
  'logs.row_created': 'ረድፍ ተፈጥሯል',
  'logs.row_updated': 'ረድፍ ተሻሽሏል',
  'logs.row_deleted': 'ረድፍ ተሰርዟል',
  'logs.slot_created': 'ቦታ ተፈጥሯል',
  'logs.slot_updated': 'ቦታ ተሻሽሏል',
  'logs.slot_deleted': 'ቦታ ተሰርዟል',
  'logs.start_date': 'መጀመሪያ ቀን',
  'logs.end_date': 'መጨረሻ ቀን',
  'logs.clear_filters': 'ማጣሪያዎችን አጽዳ',
  'logs.loading': 'የኦዲት መዝገቦችን በመጫን ላይ...',
  'logs.passport_qr': 'የፓስፖርት QR ኮድ',
  'logs.holder_name': 'የባለቤቱ ስም',
  'logs.from': 'ከ:',
  'logs.to': 'ወደ:',
  'logs.box_label': 'የሳጥን ስም (Label)',
  'logs.box_qr': 'የሳጥን QR ኮድ',
  'logs.original': 'የመጀመሪያ:',
  'logs.current': 'የአሁኑ:',
  'logs.performed_by': 'የፈጸመው አካል:',
  'logs.no_activity': 'ምንም እንቅስቃሴ አልተገኘም',
  'logs.try_adjusting': 'የፍለጋ መስፈርቶችን ወይም የቀን ማጣሪያዎችን ለማስተካከል ይሞክሩ።',

  // Security page
  'security.title': 'ደህንነት እና የተጠቃሚዎች አስተዳደር',
  'security.subtitle': 'የስርዓት ተጠቃሚዎችን እና ፍቃዶችን ያስተዳድሩ',
  'security.loading': 'በመጫን ላይ...',
  'security.total_users': 'ጠቅላላ ተጠቃሚዎች',
  'security.active_users': 'ንቁ ተጠቃሚዎች',
  'security.administrators': 'አስተዳዳሪዎች',
  'security.staff_members': 'የሰራተኛ አባላት',
  'security.rbac_matrix': 'የRBAC ፍቃድ ማትሪክስ',
  'security.rbac_subtitle': 'ለስርዓቱ አጠቃላይ ክንውኖች የተቀመጠ የደህንነት መመሪያ',
  'security.operational_actions': 'ተግባራዊ ክንውኖች',
  'security.admin_role': 'አስተዳዳሪ (Admin)',
  'security.staff_role': 'ሰራተኛ (Staff)',
  'security.action_physical_locations': 'አካላዊ መገኛዎችን መፍጠር/መሰረዝ (ክፍል፣ መደርደሪያ፣ ረድፍ፣ ቦታ)',
  'security.action_register_passports': 'ፓስፖርቶችን መመዝገብ',
  'security.action_register_boxes': 'የሚንቀሳቀሱ ሳጥኖችን መመዝገብ እና መመደብ',
  'security.action_issue_passports': 'ፓስፖርቶችን ለባለቤቶቻቸው ማስረከብ',
  'security.action_move_passports': 'ፓስፖርቶችን በሳጥኖች መካከል ማዛወር/መመደብ',
  'security.action_view_audit': 'የኦዲት መከታተያዎችን እና የስርዓት ምዝግብ ማስታወሻዎችን ማየት',
  'security.action_delete_entities': 'ሳጥኖችን/ፓስፖርቶችን/መገኛዎችን መሰረዝ',
  'security.action_manage_users': 'ተጠቃሚዎችን እና የስራ ድርሻዎችን ማስተዳደር',
  'security.user_management': 'የተጠቃሚዎች አስተዳደር',
  'security.user_management_subtitle': 'የስርዓት ተጠቃሚ መለያዎችን እና የስራ ድርሻዎችን ያስተዳድሩ',
  'security.create_user_btn': 'ተጠቃሚ ፍጠር',
  'security.search_placeholder': 'ተጠቃሚዎችን በስም ወይም በኢሜይል ፈልግ...',
  'security.loading_users': 'ተጠቃሚዎችን በመጫን ላይ...',
  'security.no_users_matching': 'ከፍለጋዎ ጋር የሚዛመድ ተጠቃሚ አልተገኘም',
  'security.no_users_found': 'ምንም ተጠቃሚ አልተገኘም',
  'security.table_user': 'ተጠቃሚ',
  'security.table_email': 'ኢሜይል',
  'security.table_status': 'ሁኔታ',
  'security.table_role': 'ድርሻ',
  'security.table_activity': 'እንቅስቃሴ',
  'security.table_actions': 'ተግባራት',
  'security.current_user_indicator': '(እርስዎ)',
  'security.logs_count': '{count} ምዝግብ ማስታወሻዎች',
  'security.cannot_modify_own': 'የራስዎን መለያ ማሻሻል አይችሉም',
  'security.status_active': 'ንቁ',
  'security.status_inactive': 'ንቁ ያልሆነ',
  'security.admin_only_msg': 'የተጠቃሚዎች አስተዳደር ለአስተዳዳሪዎች ብቻ የሚፈቀድ ነው',
  'security.toast_create_success': 'ተጠቃሚ በተሳካ ሁኔታ ተፈጥሯል',
  'security.toast_create_fail': 'ተጠቃሚ መፍጠር አልተቻለም',
  'security.toast_role_success': 'የተጠቃሚው ድርሻ በተሳካ ሁኔታ ወደ {role} ተቀይሯል',
  'security.toast_role_fail': 'የተጠቃሚውን ድርሻ መቀየር አልተቻለም',
  'security.toast_status_success': 'የተጠቃሚው ሁኔታ በተሳካ ሁኔታ ተሻሽሏል',
  'security.toast_status_fail': 'የተጠቃሚውን ሁኔታ ማሻሻል አልተቻለም',
  'security.toast_delete_success': 'ተጠቃሚ በተሳካ ሁኔታ ተሰርዟል',
  'security.toast_delete_fail': 'ተጠቃሚውን መሰረዝ አልተቻለም',
  'security.confirm_role_title': 'የድርሻ ለውጥ ማረጋገጫ',
  'security.confirm_role_msg': 'እርግጠኛ ነዎት የዚህን ተጠቃሚ የስራ ድርሻ ወደ {role} መቀየር ይፈልጋሉ?',
  'security.change_role_btn': 'ድርሻ ቀይር',
  'security.toggle_status_title': 'ተጠቃሚን {status}',
  'security.toggle_status_msg': 'እርግጠኛ ነዎት {name} ተጠቃሚን {action} ማድረግ ይፈልጋሉ?',
  'security.deactivate': 'አቦዝን',
  'security.activate': 'አግብር',
  'security.deactivate_action': 'ማቦዘን',
  'security.activate_action': 'ማግበር',
  'security.delete_user_title': 'ተጠቃሚን ሰርዝ',
  'security.delete_user_msg': 'እርግጠኛ ነዎት {name} በቋሚነት መሰረዝ ይፈልጋሉ? ይህ ድርጊት ወደኋላ መመለስ አይቻልም።',
  'security.delete_user_confirm': 'ተጠቃሚን ሰርዝ',

  // Security Modal
  'security.modal_create_title': 'አዲስ ተጠቃሚ ፍጠር',
  'security.modal_name_label': 'ስም *',
  'security.modal_name_placeholder': 'ሙሉ ስም ያስገቡ',
  'security.modal_email_label': 'ኢሜይል *',
  'security.modal_email_placeholder': 'user@example.com',
  'security.modal_role_label': 'ድርሻ *',
  'security.modal_role_staff': 'ሰራተኛ (Staff) - የተገደበ ፍቃድ',
  'security.modal_role_admin': 'አስተዳዳሪ (Admin) - ሙሉ ፍቃድ',
  'security.modal_password_label': 'የይለፍ ቃል *',
  'security.modal_password_placeholder': 'የይለፍ ቃል ያስገቡ',
  'security.modal_confirm_password_label': 'የይለፍ ቃል ያረጋግጡ *',
  'security.modal_confirm_password_placeholder': 'የይለፍ ቃል ያረጋግጡ',
  'security.modal_err_email_required': 'ኢሜይል ያስፈልጋል',
  'security.modal_err_email_invalid': 'ትክክለኛ ያልሆነ የኢሜይል አድራሻ',
  'security.modal_err_name_len': 'ስም ቢያንስ 2 ቁምፊዎች መሆን አለበት',
  'security.modal_err_password_required': 'የይለፍ ቃል ያስፈልጋል',
  'security.modal_creating': 'በመፍጠር ላይ...',
  'security.modal_create_btn': 'ተጠቃሚ ፍጠር',

  // Profile page
  'profile.title': 'የተጠቃሚ መገለጫ ቅንብሮች',
  'profile.subtitle': 'የመገለጫ መረጃዎን ያስተዳድሩ',
  'profile.loading': 'መገለጫ በመጫን ላይ...',
  'profile.failed_load': 'መገለጫውን መጫን አልተቻለም',
  'profile.info_title': 'የመገለጫ መረጃ',
  'profile.info_subtitle': 'የመለያዎን ዝርዝሮች እዚህ ይመልከቱ እና ያስተዳድሩ',
  'profile.edit_details': 'ዝርዝሮችን አሻሽል',
  'profile.status_active': 'ንቁ',
  'profile.status_inactive': 'ንቁ ያልሆነ',
  'profile.full_name': 'ሙሉ ስም',
  'profile.email': 'የኢሜይል አድራሻ',
  'profile.email_immutable': 'የኢሜይል አድራሻን መቀየር አይቻልም።',
  'profile.cancel': 'ሰርዝ',
  'profile.saving': 'በማስቀመጥ ላይ...',
  'profile.save_changes': 'ለውጦችን አስቀምጥ',
  'profile.user_id': 'የተጠቃሚ መለያ ቁጥር (ID)',
  'profile.member_since': 'አባል የሆኑበት ቀን',
  'profile.password_security': 'የይለፍ ቃል እና ደህንነት',
  'profile.password_subtitle': 'የይለፍ ቃልዎን እና የመለያዎን ደህንነት ያስተዳድሩ',
  'profile.change_password_btn': 'የይለፍ ቃል ቀይር',
  'profile.current_password': 'የአሁኑ የይለፍ ቃል',
  'profile.current_password_placeholder': 'የአሁኑን የይለፍ ቃል ያስገቡ',
  'profile.new_password': 'አዲስ የይለፍ ቃል',
  'profile.new_password_placeholder': 'አዲስ የይለፍ ቃል ያስገቡ',
  'profile.password_strength': 'የይለፍ ቃል ጥንካሬ:',
  'profile.strength_weak': 'ደካማ',
  'profile.strength_fair': 'መካከለኛ',
  'profile.strength_good': 'ጥሩ',
  'profile.strength_strong': 'በጣም ጠንካራ',
  'profile.password_rules': 'ይህ የይለፍ ቃል ቢያንስ 8 ቁምፊዎች ሆኖ አቢይ ፊደል፣ ንዑስ ፊደል፣ ቁጥር እና ልዩ ምልክት መያዝ አለበት',
  'profile.confirm_password': 'አዲሱን የይለፍ ቃል ያረጋግጡ',
  'profile.confirm_password_placeholder': 'አዲሱን የይለፍ ቃል በድጋሚ ያስገቡ',
  'profile.changing_password': 'የይለፍ ቃል በመቀየር ላይ...',
  'profile.password_active': 'የይለፍ ቃል ጥበቃ ንቁ ነው',
  'profile.password_active_desc': 'መለያዎ በጠንካራ የይለፍ ቃል የተጠበቀ ነው',
  'profile.toast_details_success': 'የመገለጫ መረጃዎ በተሳካ ሁኔታ ተሻሽሏል',
  'profile.toast_details_fail': 'የመገለጫ መረጃውን ማሻሻል አልተቻለም',
  'profile.err_current_required': 'የአሁኑ የይለፍ ቃል ያስፈልጋል',
  'profile.err_new_required': 'አዲስ የይለፍ ቃል ያስፈልጋል',
  'profile.err_len_min': 'የይለፍ ቃል ቢያንስ 8 ቁምፊዎች መሆን አለበት',
  'profile.err_uppercase': 'የይለፍ ቃል ቢያንስ አንድ አቢይ ፊደል (uppercase) መያዝ አለበት',
  'profile.err_lowercase': 'የይለፍ ቃል ቢያንስ አንድ ንዑስ ፊደል (lowercase) መያዝ አለበት',
  'profile.err_number': 'የይለፍ ቃል ቢያንስ አንድ ቁጥር መያዝ አለበት',
  'profile.err_special': 'የይለፍ ቃል ቢያንስ አንድ ልዩ ምልክት መያዝ አለበት',
  'profile.err_mismatch': 'የይለፍ ቃላቱ አይዛመዱም',
  'profile.err_must_differ': 'አዲሱ የይለፍ ቃል ከአሁኑ የይለፍ ቃል የተለየ መሆን አለበት',
  'profile.toast_password_success': 'የይለፍ ቃል በተሳካ ሁኔታ ተቀይሯል',
  'profile.toast_password_fail': 'የይለፍ ቃል መቀየር አልተቻለም',

  // Setup page
  'setup.title': 'የስርዓት መጀመሪያ ማዋቀሪያ',
  'setup.subtitle': 'አጠቃላይ የስርዓት መረጃዎችን እዚህ ይቆጣጠሩ',
};

const englishTranslations: Translations = {
  // Sidebar
  'sidebar.main': 'MAIN',
  'sidebar.management': 'MANAGEMENT',
  'sidebar.settings': 'SETTINGS',
  'sidebar.dashboard': 'Dashboard',
  'sidebar.passports': 'Passports',
  'sidebar.boxes': 'Boxes',
  'sidebar.structure': 'Structure',
  'sidebar.logs': 'Audit Logs',
  'sidebar.profile': 'Profile',
  'sidebar.security': 'Security',
  'sidebar.setup': 'Setup',
  'sidebar.reports': 'Reports',
  'sidebar.logout': 'Logout',

  // Header
  'header.search_placeholder': 'Search passports, boxes, slots...',
  'header.profile_tooltip': 'View Profile',
  'header.search_no_results': 'No results found',
  'header.search_searching': 'Searching...',
  'header.search_min_char': 'Type at least 2 characters',

  // Dashboard
  'dashboard.title': 'Dashboard Overview',
  'dashboard.subtitle': 'Real-time tracking summary',
  'dashboard.total_boxes': 'Total Movable Boxes',
  'dashboard.total_boxes_sub': 'All registered boxes',
  'dashboard.occupied_boxes': 'Occupied Boxes',
  'dashboard.occupied_boxes_sub': 'Currently in use',
  'dashboard.vacant_boxes': 'Vacant Boxes',
  'dashboard.vacant_boxes_sub': 'Available for use',
  'dashboard.occupancy_rate': 'Occupancy Rate',
  'dashboard.occupancy_rate_sub': 'Overall utilization',
  'dashboard.table_title': 'Movable Box Overview',
  'dashboard.refresh': 'Refresh',
  'dashboard.showing_recent': 'Showing most recent',
  'dashboard.view_all': 'View all',
  'dashboard.col_box_id': 'Box ID',
  'dashboard.col_label': 'Label',
  'dashboard.col_location': 'Location',
  'dashboard.col_occupied': 'Occupied',
  'dashboard.col_capacity': 'Capacity',
  'dashboard.col_status': 'Status',
  'dashboard.loading_stats': 'Loading dashboard statistics...',
  'dashboard.activity_trend': 'Passport Activity Trend',
  'dashboard.activity_trend_sub': 'Weekly volume of passport returns and issues',
  'dashboard.room_capacity': 'Room Capacity Utilization',
  'dashboard.room_capacity_sub': 'Occupied slots vs total capacity',

  // Passports page
  'passports.title': 'Passport Registry',
  'passports.subtitle': 'Manage and track all passports',
  'passports.add_passport': 'Register New Passport',
  'passports.search_placeholder': 'Search by name, ID number, or QR...',
  'passports.col_holder': 'Holder',
  'passports.col_passport_no': 'Passport No',
  'passports.col_qr_code': 'QR Code',
  'passports.col_status': 'Status',
  'passports.status_active': 'Active',
  'passports.status_inactive': 'Inactive',
  'passports.custody_title': 'Passport Custody System',
  'passports.custody_subtitle': 'Track and register national passports',
  'passports.custody_subtitle_count': 'total passports in database',
  'passports.all_title': 'All Registered Passports',
  'passports.all_statuses': 'All Statuses',
  'passports.status_in_box': 'In Box',
  'passports.status_issued': 'Issued',
  'passports.selected_count': 'Passport(s) Selected',
  'passports.batch_assign': 'Batch Assign to Box',
  'passports.clear_selection': 'Clear Selection',
  'passports.col_holder_id': 'Holder ID No',
  'passports.col_box': 'Box Storage',
  'passports.col_actions': 'Actions',
  'passports.action_move': 'Move',
  'passports.action_return': 'Return',
  'passports.action_issue': 'Issue',
  'passports.no_results': 'No passports found',
  'passports.no_records': 'No passports registered',
  'passports.try_different': 'Try a different search or filter',
  'passports.register_to_begin': 'Register a new passport to begin tracking',
  'passports.prev': 'Prev',
  'passports.next': 'Next',
  'passports.of': 'of',
  'passports.records': 'records',
  'passports.modal_register_title': 'Register New Passport',
  'passports.field_qr': 'QR Code / Document Number *',
  'passports.field_name': 'Holder Full Name *',
  'passports.field_id': 'National / Document ID No *',
  'passports.cancel': 'Cancel',
  'passports.registering': 'Registering...',
  'passports.register': 'Register',
  'passports.modal_batch_title': 'Batch Assign to Movable Box',
  'passports.modal_assign_title': 'Assign Passport to Box',
  'passports.selected_count_sub': 'selected passports',
  'passports.boxes_avail': 'boxes available',
  'passports.passport_of': 'passport belonging to',
  'passports.search_box_placeholder': 'Search by label or QR code...',
  'passports.loading_boxes': 'Loading boxes...',
  'passports.no_available_boxes': 'No available boxes with sufficient vacant slots',
  'passports.need_boxes_with': 'Need boxes with at least',
  'passports.vacant_slots': 'vacant slots',
  'passports.vacant_count': 'vacant',
  'passports.assigning': 'Assigning...',
  'passports.assign': 'Assign',
  'passports.modal_issue_title': 'Issue Passport',
  'passports.issue_msg_1': 'Issue passport belonging to',
  'passports.issue_msg_2': 'to its owner?',
  'passports.modal_delete_title': 'Confirm Deletion',
  'passports.delete_msg_1': 'Are you sure you want to delete passport belonging to',
  'passports.delete_msg_2': 'This action cannot be undone.',
  'passports.delete': 'Delete',

  // Boxes page
  'boxes.title': 'Movable Boxes',
  'boxes.subtitle': 'Manage box inventory and assignments',
  'boxes.add_box': 'Create New Box',
  'boxes.all_title': 'All Movable Boxes',
  'boxes.selected_count': 'boxes selected',
  'boxes.total_count': 'boxes in system',
  'boxes.assign_to_slots': 'Assign Boxes to Slots',
  'boxes.bulk_register': 'Bulk Register',
  'boxes.search_placeholder': 'Search Box ID, Label...',
  'boxes.all_status': 'All Status',
  'boxes.status_active': 'Active',
  'boxes.status_full': 'Full',
  'boxes.status_inactive': 'Inactive',
  'boxes.col_box_id': 'Box ID',
  'boxes.col_label': 'Label',
  'boxes.col_location': 'Location',
  'boxes.col_occupied': 'Occupied',
  'boxes.col_capacity': 'Capacity',
  'boxes.col_status': 'Status',
  'boxes.col_actions': 'Actions',
  'boxes.unassigned': 'Unassigned',
  'boxes.action_move_tooltip': 'Move to slot',
  'boxes.cannot_delete_occupied': 'Cannot delete occupied box',
  'boxes.delete_box': 'Delete box',
  'boxes.no_results': 'No boxes found',
  'boxes.no_records': 'No boxes yet',
  'boxes.try_different': 'Try a different search or filter',
  'boxes.add_to_begin': 'Start by adding a box to the system',
  'boxes.modal_create_title': 'Add New Box',
  'boxes.field_qr': 'QR Code *',
  'boxes.field_label': 'Label *',
  'boxes.field_capacity': 'Capacity',
  'boxes.capacity_help': 'Default capacity is 10 passports per box',
  'boxes.creating': 'Creating...',
  'boxes.create': 'Create Box',
  'boxes.modal_move_title': 'Move Box',
  'boxes.select_slot_help': 'Select a slot to assign this box',
  'boxes.slots_available': 'slots available',
  'boxes.search_slot_placeholder': 'Search slot by name, room, or QR code...',
  'boxes.no_slots_found': 'No slots found matching your search',
  'boxes.no_slots_configured': 'No slots configured',
  'boxes.moving': 'Moving...',
  'boxes.modal_bulk_title': 'Bulk Register Boxes',
  'boxes.bulk_register_help': 'Register multiple boxes at once with sequential labeling',
  'boxes.field_label_pattern': 'Label Pattern',
  'boxes.label_pattern_help': 'Use {n} for number. Add :04d for zero-padding...',
  'boxes.field_qr_pattern': 'QR Code Pattern',
  'boxes.qr_pattern_help': 'QR codes must be globally unique. Use same pattern format as label.',
  'boxes.field_start_number': 'Start Number',
  'boxes.field_end_number': 'End Number',
  'boxes.preview': 'Preview',
  'boxes.boxes_count_suffix': 'boxes',
  'boxes.and': 'and',
  'boxes.more': 'more',
  'boxes.registering': 'Registering...',
  'boxes.register': 'Register',
  'boxes.modal_bulk_assign_title': 'Bulk Assign Boxes to Slots',
  'boxes.bulk_assign_help': 'Automatically assign selected boxes to available slots',
  'boxes.field_room_filter': 'Filter by Room (Optional)',
  'boxes.all_rooms': 'All Rooms (any available slot)',
  'boxes.assign_slots_help': 'Boxes will be assigned to the first available slots',
  'boxes.in_room': 'in the selected room',
  'boxes.selected_boxes_heading': 'SELECTED BOXES',
  'boxes.assigning': 'Assigning...',
  'boxes.assign': 'Assign',
  'boxes.delete_confirm_msg': 'Are you sure you want to delete box',

  // Structure page
  'structure.title': 'Physical Structure Layout',
  'structure.subtitle': 'Configure rooms, shelves, rows and slots',
  'structure.structure_details': 'STRUCTURE DETAILS',
  'structure.room_details': 'Room Details',
  'structure.shelf_details': 'Shelf Details',
  'structure.row_details': 'Row Details',
  'structure.slot_details': 'Slot Details',
  'structure.hierarchy': 'Storage Facility Hierarchy',
  'structure.central_repo': 'Central Repository System (CRS-01)',
  'structure.add_room': 'Add Room',
  'structure.no_rooms': 'No Rooms Configured',
  'structure.add_room_to_begin': 'Start by adding a room to the system.',
  'structure.details': 'Details',
  'structure.details_title': 'Details Panel',
  'structure.select_item_to_view': 'Select an item in the structure tree to view details',
  'structure.location_path': 'LOCATION PATH',
  'structure.qr_code': 'QR CODE',
  'structure.status': 'STATUS',
  'structure.occupied': 'Occupied',
  'structure.available': 'Available',
  'structure.assign_box_to_slot': 'Assign Box to Slot',
  'structure.room_name': 'ROOM NAME',
  'structure.shelf_name': 'SHELF NAME',
  'structure.row_name': 'ROW NAME',
  'structure.slot_name': 'SLOT NAME',
  'structure.details_shelves': 'Contains {count} shelves',
  'structure.details_rows': 'Contains {count} rows',
  'structure.details_slots': 'Contains {count} slots',
  'structure.created_at': 'CREATED AT',
  'structure.parent_room': 'PARENT ROOM',
  'structure.parent_shelf': 'PARENT SHELF',
  'structure.position': 'POSITION',
  'structure.add': 'Add',
  'structure.edit': 'Edit',
  'structure.save': 'Save',
  'structure.saving': 'Saving...',
  'structure.creating': 'Creating...',
  'structure.cancel': 'Cancel',
  'structure.name': 'Name',
  'structure.position_label': 'Position',
  'structure.no_boxes_available': 'No available boxes',
  'structure.bulk_create_slots': 'Bulk Create Slots',
  'structure.bulk_create_slots_help': 'Create multiple slots at once with sequential naming',
  'structure.name_pattern': 'Name Pattern',
  'structure.qr_pattern': 'QR Code Pattern',
  'structure.use_n_placeholder': 'Use {n} for number placeholder (e.g., "Slot {n}" → Slot 1, Slot 2...)',
  'structure.use_qr_placeholder': 'Use {n} for number, {row} for row name (e.g., "SLOT-{row}-{n}" → SLOT-A-1, SLOT-A-2...)',
  'structure.current_row': 'Current row:',
  'structure.start_number': 'Start Number',
  'structure.end_number': 'End Number',
  'structure.position_start': 'Position Start',
  'structure.preview': 'Preview',
  'structure.preview_slots_title': 'Preview (first 3 of {total} slots):',
  'structure.and_more': '... and {count} more',
  'structure.create_slots_btn': 'Create {count} Slots',
  'structure.bulk_create_rows': 'Bulk Create Rows',
  'structure.bulk_create_rows_help': 'Create multiple rows at once with letter sequence (A-Z)',
  'structure.use_letter_placeholder': 'Use {letter} for letter placeholder (e.g., "Row {letter}" → Row A, Row B...)',
  'structure.use_qr_letter_placeholder': 'Use {letter} for letter placeholder (e.g., "ROW-{letter}" → ROW-A, ROW-B...)',
  'structure.letter_sequence': 'Letter Sequence',
  'structure.sequence_help': 'Format: START-END (e.g., "A-Z" for all letters, "A-J" for first 10)',
  'structure.preview_first_3': 'Preview (first 3):',
  'structure.and_more_total': '... and {count} more ({total} total)',
  'structure.create_rows_btn': 'Create Rows {sequence}',
  'structure.confirm_delete': 'Confirm Deletion',
  'structure.confirm_delete_msg': 'Are you sure you want to delete {name}? This action cannot be undone.',
  'structure.delete': 'Delete',
  'structure.edit_room': 'Edit Room',
  'structure.add_shelf': 'Add Shelf',
  'structure.edit_shelf': 'Edit Shelf',
  'structure.add_row': 'Add Row',
  'structure.edit_row': 'Edit Row',
  'structure.add_slot': 'Add Slot',
  'structure.edit_slot': 'Edit Slot',
  'structure.bulk_rows_btn': 'Bulk',
  'structure.bulk_slots_btn': 'Bulk',

  // Logs page
  'logs.title': 'Audit Logs',
  'logs.subtitle': 'Real-time movement ledger and system operation logs',
  'logs.activity_timeline': 'Activity Timeline',
  'logs.entries_found': 'log entries found',
  'logs.text_search': 'TEXT SEARCH',
  'logs.search_placeholder': 'Search holder, QR, box, staff...',
  'logs.action_type': 'ACTION TYPE',
  'logs.all_actions': 'All Actions',
  'logs.physical_movements': 'Physical Movements',
  'logs.passport_assigned': 'Passport Placed',
  'logs.passport_returned': 'Returned to Vault',
  'logs.passport_issued': 'Issued to Owner',
  'logs.box_moved': 'Box Relocated',
  'logs.config_changes': 'Configuration Changes',
  'logs.room_created': 'Room Created',
  'logs.room_updated': 'Room Updated',
  'logs.room_deleted': 'Room Deleted',
  'logs.shelf_created': 'Shelf Created',
  'logs.shelf_updated': 'Shelf Updated',
  'logs.shelf_deleted': 'Shelf Deleted',
  'logs.row_created': 'Row Created',
  'logs.row_updated': 'Row Updated',
  'logs.row_deleted': 'Row Deleted',
  'logs.slot_created': 'Slot Created',
  'logs.slot_updated': 'Slot Updated',
  'logs.slot_deleted': 'Slot Deleted',
  'logs.start_date': 'START DATE',
  'logs.end_date': 'END DATE',
  'logs.clear_filters': 'Clear Filters',
  'logs.loading': 'Loading audit ledger...',
  'logs.passport_qr': 'Passport QR Code',
  'logs.holder_name': 'Holder Name',
  'logs.from': 'From:',
  'logs.to': 'To:',
  'logs.box_label': 'Box Label',
  'logs.box_qr': 'Box QR Code',
  'logs.original': 'Original:',
  'logs.current': 'Current:',
  'logs.performed_by': 'Performed by:',
  'logs.no_activity': 'No Activity Found',
  'logs.try_adjusting': 'Try adjusting your search criteria or date filters.',

  // Security page
  'security.title': 'Security & User Management',
  'security.subtitle': 'Manage system users and access levels',
  'security.loading': 'Loading...',
  'security.total_users': 'Total Users',
  'security.active_users': 'Active Users',
  'security.administrators': 'Administrators',
  'security.staff_members': 'Staff Members',
  'security.rbac_matrix': 'RBAC Permission Matrix',
  'security.rbac_subtitle': 'System-wide security policy for all operational actions',
  'security.operational_actions': 'Operational Actions',
  'security.admin_role': 'Admin',
  'security.staff_role': 'Staff',
  'security.action_physical_locations': 'Create/Delete Physical Locations (Room, Shelf, Row, Slot)',
  'security.action_register_passports': 'Register Passports',
  'security.action_register_boxes': 'Register & Assign Movable Boxes',
  'security.action_issue_passports': 'Issue Passports to Owners',
  'security.action_move_passports': 'Assign/Move Passports Between Boxes',
  'security.action_view_audit': 'View Audit Trails & System Logs',
  'security.action_delete_entities': 'Delete Boxes/Passports/Locations',
  'security.action_manage_users': 'Manage Users & Roles',
  'security.user_management': 'User Management',
  'security.user_management_subtitle': 'Manage system operator accounts and role assignments',
  'security.create_user_btn': 'Create User',
  'security.search_placeholder': 'Search users by name or email...',
  'security.loading_users': 'Loading users...',
  'security.no_users_matching': 'No users found matching your search',
  'security.no_users_found': 'No users found',
  'security.table_user': 'User',
  'security.table_email': 'Email',
  'security.table_status': 'Status',
  'security.table_role': 'Role',
  'security.table_activity': 'Activity',
  'security.table_actions': 'Actions',
  'security.current_user_indicator': '(You)',
  'security.logs_count': '{count} logs',
  'security.cannot_modify_own': 'Cannot modify own account',
  'security.status_active': 'Active',
  'security.status_inactive': 'Inactive',
  'security.admin_only_msg': 'User management is only accessible to administrators.',
  'security.toast_create_success': 'User created successfully',
  'security.toast_create_fail': 'Failed to create user',
  'security.toast_role_success': 'User role changed to {role} successfully',
  'security.toast_role_fail': 'Failed to change user role',
  'security.toast_status_success': 'User status updated successfully',
  'security.toast_status_fail': 'Failed to update user status',
  'security.toast_delete_success': 'User deleted successfully',
  'security.toast_delete_fail': 'Failed to delete user',
  'security.confirm_role_title': 'Confirm Role Change',
  'security.confirm_role_msg': "Are you sure you want to change this user's role to {role}?",
  'security.change_role_btn': 'Change Role',
  'security.toggle_status_title': '{status} User',
  'security.toggle_status_msg': 'Are you sure you want to {action} {name}?',
  'security.deactivate': 'Deactivate',
  'security.activate': 'Activate',
  'security.deactivate_action': 'deactivate',
  'security.activate_action': 'activate',
  'security.delete_user_title': 'Delete User',
  'security.delete_user_msg': 'Are you sure you want to permanently delete {name}? This action cannot be undone.',
  'security.delete_user_confirm': 'Delete User',

  // Security Modal
  'security.modal_create_title': 'Create New User',
  'security.modal_name_label': 'Name *',
  'security.modal_name_placeholder': 'Enter full name',
  'security.modal_email_label': 'Email *',
  'security.modal_email_placeholder': 'user@example.com',
  'security.modal_role_label': 'Role *',
  'security.modal_role_staff': 'Staff - Limited Permissions',
  'security.modal_role_admin': 'Admin - Full Access',
  'security.modal_password_label': 'Password *',
  'security.modal_password_placeholder': 'Enter password',
  'security.modal_confirm_password_label': 'Confirm Password *',
  'security.modal_confirm_password_placeholder': 'Confirm password',
  'security.modal_err_email_required': 'Email is required',
  'security.modal_err_email_invalid': 'Invalid email address',
  'security.modal_err_name_len': 'Name must be at least 2 characters',
  'security.modal_err_password_required': 'Password is required',
  'security.modal_creating': 'Creating...',
  'security.modal_create_btn': 'Create User',

  // Profile page
  'profile.title': 'User Profile Settings',
  'profile.subtitle': 'Manage your personal profile information',
  'profile.loading': 'Loading profile...',
  'profile.failed_load': 'Failed to load profile',
  'profile.info_title': 'Profile Information',
  'profile.info_subtitle': 'View and manage your account details',
  'profile.edit_details': 'Edit Details',
  'profile.status_active': 'Active',
  'profile.status_inactive': 'Inactive',
  'profile.full_name': 'Full Name',
  'profile.email': 'Email Address',
  'profile.email_immutable': 'Email address cannot be changed.',
  'profile.cancel': 'Cancel',
  'profile.saving': 'Saving...',
  'profile.save_changes': 'Save Changes',
  'profile.user_id': 'User ID',
  'profile.member_since': 'Member Since',
  'profile.password_security': 'Password & Security',
  'profile.password_subtitle': 'Manage your password and account security',
  'profile.change_password_btn': 'Change Password',
  'profile.current_password': 'Current Password',
  'profile.current_password_placeholder': 'Enter current password',
  'profile.new_password': 'New Password',
  'profile.new_password_placeholder': 'Enter new password',
  'profile.password_strength': 'Password strength:',
  'profile.strength_weak': 'Weak',
  'profile.strength_fair': 'Fair',
  'profile.strength_good': 'Good',
  'profile.strength_strong': 'Strong',
  'profile.password_rules': 'Must be 8+ characters with uppercase, lowercase, number, and special character',
  'profile.confirm_password': 'Confirm New Password',
  'profile.confirm_password_placeholder': 'Confirm new password',
  'profile.changing_password': 'Changing Password...',
  'profile.password_active': 'Password Protection Active',
  'profile.password_active_desc': 'Your account is secured with a strong password',
  'profile.toast_details_success': 'Profile details updated successfully',
  'profile.toast_details_fail': 'Failed to update profile details',
  'profile.err_current_required': 'Current password is required',
  'profile.err_new_required': 'New password is required',
  'profile.err_len_min': 'Password must be at least 8 characters',
  'profile.err_uppercase': 'Password must contain at least one uppercase letter',
  'profile.err_lowercase': 'Password must contain at least one lowercase letter',
  'profile.err_number': 'Password must contain at least one number',
  'profile.err_special': 'Password must contain at least one special character',
  'profile.err_mismatch': 'Passwords do not match',
  'profile.err_must_differ': 'New password must be different from current password',
  'profile.toast_password_success': 'Password changed successfully',
  'profile.toast_password_fail': 'Failed to change password',

  // Setup page
  'setup.title': 'System Initialization Setup',
  'setup.subtitle': 'Configure system defaults and meta metadata',
};

interface LanguageContextProps {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string, defaultValue?: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>('en');
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
    const savedLocale = localStorage.getItem('locale') as Locale;
    if (savedLocale === 'en' || savedLocale === 'am') {
      setLocaleState(savedLocale);
    }
  }, []);

  const setLocale = (newLocale: Locale) => {
    setLocaleState(newLocale);
    localStorage.setItem('locale', newLocale);
  };

  const t = (key: string, defaultValue?: string): string => {
    const translations = locale === 'am' ? amharicTranslations : englishTranslations;
    return translations[key] || defaultValue || key;
  };

  // SSR Safe rendering (defaults to English on server, updates on mount)
  return (
    <LanguageContext.Provider value={{ locale: isMounted ? locale : 'en', setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
}
